version: "3.9"
services:
  dev-container:
    build:
      dockerfile: ./.devcontainer/Dockerfile
      context: ./
    volumes:
      - .:/workspaces/cicd:cached
      - ~/.aws:/root/.aws:ro
    command: /bin/sh -c "while sleep 1000; do :; done"
