name: terraform-docs
description: "Check Terraform configuration documentation"

inputs:
  configuration:
    description: "Name of the Terraform configuration to analyze"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Terraform docs
      shell: bash
      run: |
        cd terraform/configurations/
        terraform-docs --output-file TERRAFORM_DOCS.md .
        cmp ${{ inputs.configuration }}/TERRAFORM_DOCS.md ${{ inputs.configuration }}/README.md
