script: 
  description: Import Terraform Configuration Into State
  interpreter: SHELL
  scripts: 
    - |-
      # unhide the imports file temporarily for import-specific task
      mv ${bamboo.configurationDirectory}/.imports.tf ${bamboo.configurationDirectory}/imports.tf

      terraform -chdir=${bamboo.configurationDirectory} refresh -var-file=${bamboo.tfvarsFile}

      mv ${bamboo.configurationDirectory}/imports.tf ${bamboo.configurationDirectory}/.imports.tf
