script:
  description: Validate Terraform Documentation
  interpreter: SHELL
  scripts:
    - |-
      # run terraform-docs using config file and compare validation to repository README
        terraform-docs --output-file TERRAFORM_DOCS.md terraform/configurations/
        cmp "${bamboo.configurationDirectory}/TFDOCS_VALIDATION.md" "${bamboo.configurationDirectory}/README.md"
