script: 
  description: Apply Terraform Configuration
  interpreter: SHELL
  scripts: 
    - |-
      #!/bin/bash
      terraform -chdir=${bamboo.configurationDirectory} apply -auto-approve -var-file=${bamboo.tfvarsFile} 
