script: 
  description: Destroy Terraform Configuration
  interpreter: SHELL
  scripts: 
    - |-
      terraform -chdir=${bamboo.configurationDirectory} destroy -auto-approve -var-file=${bamboo.tfvarsFile}
