script: 
  description: Generate Configuration Terraform Plan
  interpreter: SHELL
  scripts: 
    - |-
      #!/bin/bash
      terraform -chdir=${bamboo.configurationDirectory} plan -var-file=${bamboo.tfvarsFile}
