script: 
  description: Validate Terraform Documentation
  interpreter: SHELL
  scripts: 
    - |-
      #!/bin/bash
      [ -f "${bamboo.configurationDirectory}/README.md" ] || { echo "${bamboo.configurationDirectory}/README.md NOT FOUND" ; exit 1 ;}
