name: terraform-validate
description: "Validate Terraform configuration"

inputs:
  tf_configuration_path:
    description: "Filepath Terraform configuration to analyze"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Terraform validate
      shell: bash
      run: |
        terraform -chdir=${{ inputs.tf_configuration_path }} init -backend=false
        terraform -chdir=${{ inputs.tf_configuration_path }} validate
