key: TFSEC
description: Analyze Terraform Configuration Security
docker:
  image: ${bamboo.containerRegistryName}/${bamboo.planRepository.name}:${bamboo.planRepository.branchName}
  volumes:
    ${bamboo.working.directory}: ${bamboo.working.directory}
    ${bamboo.tmp.directory}: ${bamboo.tmp.directory}
  docker-run-arguments: []
tasks:
  - !include tasks/checkout-repository.yaml
  - !include tasks/terraform-security.yaml
artifact-subscriptions: []
