name: 'Terraform Import'
description: 'Temporarily unhides imports and runs terraform refresh'
inputs:
  configuration:
    description: 'Name of the configuration'
    required: true
  environment:
    description: 'Configuration environment'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Terraform import
      shell: bash
      run: |
        mv terraform/configurations/${{ inputs.configuration }}/.imports.tf terraform/configurations/${{ inputs.configuration }}/imports.tf
        terraform -chdir=terraform/configurations/${{ inputs.configuration }} refresh -var-file=env/${{ inputs.environment }}.tfvars || true
        mv terraform/configurations/${{ inputs.configuration }}/imports.tf terraform/configurations/${{ inputs.configuration }}/.imports.tf
