name: 'Terraform Lint'
description: 'Runs tflint on a Terraform configuration'
inputs:
  configuration:
    description: 'Name of the configuration'
    required: true
  environment:
    description: 'Configuration environment'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Terraform lint
      shell: bash
      run: |
        tflint --chdir=terraform/configurations/${{ inputs.configuration }} --minimum-failure-severity=error --var-file=env/${{ inputs.environment }}.tfvars
