script: 
  description: Build Docker Image
  interpreter: SHELL
  scripts: 
    - |-
      docker buildx build \
        --file ${bamboo.dockerfilePath} \
        --tag ${bamboo.containerRegistryName}/${bamboo.planRepository.name}:${bamboo.planRepository.branchName} \
        .
