name: approval

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        description: 'Name of GitHub environment used for reviews'

jobs:
  approval:
    runs-on: ubuntu-latest
    steps:
    - name: approval
      uses: ./platforms/github/composite-actions/approval/approval.yaml
      with:
        environment: ${{ inputs.environment }}
