name: approval

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        description: 'Name of GitHub environment used for reviews'

jobs:
  approval:
    runs-on: ubuntu-24.04
    steps:
    - name: ls
      run: ls -la
      
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: ls2
      run: ls -la

    - name: approval
      uses: ./platforms/github/composite-actions/approval
      with:
        environment: ${{ inputs.environment }}
