name: container-build-and-push

on:
  workflow_call:
    inputs:
      dockerfile:
        description: 'Name of GitHub environment used for reviews'
        required: false
        type: string
        default: './.devcontainer/Dockerfile'

jobs:
  build-and-push:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Container build and push
      uses: ./.github/workflows/container-build-and-push.yaml
