name: container-build-and-push

on:
  workflow_call:
    secrets:
      DOCKER_HUB_ID:
        required: true
      DOCKER_HUB_ACCESS_TOKEN:
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Container build and push
      uses: ./platforms/github/composite-actions/container-build-and-push
      with:
        dockerhub_id: ${{ secrets.DOCKER_HUB_ID }}
        dockerhub_access_token: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
