name: terraform-destroy

on:
  workflow_call:
    inputs:
      container_image:
        description: 'Container image name'
        type: string
        required: true
      configuration:
        description: 'Name of the configuration'
        type: string
        required: true
      environment:
        description: 'Configuration Environment, should be the same for both the backend and GitHub environment'
        type: string
        required: true
    secrets:
      AZURE_CLIENT_ID:
        description: 'Azure Service Principal Client ID'
        required: false
      AZURE_SUBSCRIPTION_ID:
        description: 'Azure Subscription ID'
        required: false
      AZURE_TENANT_ID:
        description: 'Azure Tenant ID'
        required: false

defaults:
  run:
    shell: bash

jobs:
  terraform-destroy:
    runs-on: ubuntu-24.04
    environment: ${{ inputs.environment }}
    container:
      image: ${{ inputs.container_image }}

    env:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        if: env.AZURE_CLIENT_ID != '' && env.AZURE_SUBSCRIPTION_ID != '' && env.AZURE_TENANT_ID != ''
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          
      - name: Terraform init
        run: |
          terraform -chdir=terraform/configurations/${{ inputs.configuration }} init -backend-config=env/${{ inputs.environment }}.tfbackend -reconfigure

      - name: Terraform destroy
        run: |
          terraform -chdir=terraform/configurations/${{ inputs.configuration }} destroy -auto-approve -var-file=env/${{ inputs.environment }}.tfvars
