name: terraform-restate

on:
  workflow_call:
    inputs:
      container_image:
        description: 'Container image name'
        type: string
        required: true
      configuration:
        description: 'Name of the configuration'
        type: string
        required: true
      environment:
        description: 'Configuration Environment, should be the same for both the backend and GitHub environment'
        type: string
        required: true
    secrets:
      ARM_CLIENT_ID:
        description: 'Azure Service Principal Client ID'
        required: false
      ARM_SUBSCRIPTION_ID:
        description: 'Azure Subscription ID'
        required: false
      ARM_TENANT_ID:
        description: 'Azure Tenant ID'
        required: false

defaults:
  run:
    shell: bash

jobs:
  delete-state:
    runs-on: ubuntu-24.04
    environment: ${{ inputs.environment }}
    container:
      image: ${{ inputs.container_image }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Delete Terraform statefile
        run: |
          echo todo: delete statefile somehow

  terraform-import:
    runs-on: ubuntu-24.04
    container:
      image: ${{ inputs.container_image }}

    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        if: env.ARM_CLIENT_ID != '' && env.ARM_SUBSCRIPTION_ID != '' && env.ARM_TENANT_ID != ''
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}

      - name: Terraform init
        run: |
          terraform -chdir=terraform/configurations/${{ inputs.configuration }} init -backend-config=env/${{ inputs.environment }}.tfbackend -reconfigure

      - name: Terraform import
        continue-on-error: true
        run: |
          # unhide the imports file temporarily for import-specific task
          mv terraform/configurations/${{ inputs.configuration }}/.imports.tf terraform/configurations/${{ inputs.configuration }}/imports.tf
          terraform -chdir=terraform/configurations/${{ inputs.configuration }} refresh -var-file=env/${{ inputs.environment }}.tfvars
          mv terraform/configurations/${{ inputs.configuration }}/imports.tf terraform/configurations/${{ inputs.configuration }}/.imports.tf
