name: terraform-deployment-ci

on:
  workflow_call:
    inputs:
      container_image:
        description: 'Container image name'
        type: string
        required: true
      configuration:
        description: 'Name of the configuration'
        type: string
        required: true
      environment:
        description: 'Configuration Environment, should be the same for both the backend and GitHub environment'
        type: string
        required: true
    secrets:
      AZURE_CLIENT_ID:
        description: 'Azure Service Principal Client ID'
        required: false
      AZURE_SUBSCRIPTION_ID:
        description: 'Azure Subscription ID'
        required: false
      AZURE_TENANT_ID:
        description: 'Azure Tenant ID'
        required: false

defaults:
  run:
    shell: bash

jobs:
  static-analysis:
    uses: armckinney/cicd/.github/workflows/rwf-terraform-static-analysis.yaml@main
    with:
      container_image: ${{ inputs.container_image }}
      configuration: ${{ inputs.configuration }}
      environment: ${{ inputs.environment }}

  terraform-plan:
    needs: static-analysis
    uses: armckinney/cicd/.github/workflows/rwf-terraform-plan.yaml@main
    with:
      container_image: ${{ inputs.container_image }}
      configuration: ${{ inputs.configuration }}
      environment: ${{ inputs.environment }}
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

  terraform-apply:
    needs: static-analysis
    uses: armckinney/cicd/.github/workflows/rwf-terraform-apply.yaml@main
    with:
      container_image: ${{ inputs.container_image }}
      configuration: ${{ inputs.configuration }}
      environment: ${{ inputs.environment }}
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
