name: terraform-deployment-ci

on:
  workflow_call:
    inputs:
      container_image:
        description: 'Container image name'
        type: string
        required: true
      configuration:
        description: 'Name of the configuration'
        type: string
        required: true
      environment:
        description: 'Configuration Environment, should be the same for both the backend and GitHub environment'
        type: string
        required: true
      arm_use_oidc:
        description: 'Use OIDC for Azure authentication'
        type: boolean
        default: false
        required: false
    secrets:
      ARM_CLIENT_ID:
        description: 'Azure Service Principal Client ID'
        required: false
      ARM_SUBSCRIPTION_ID:
        description: 'Azure Subscription ID'
        required: false
      ARM_TENANT_ID:
        description: 'Azure Tenant ID'
        required: false
      ARM_CLIENT_SECRET:
        description: 'Azure Service Principal Client Secret'
        required: false

defaults:
  run:
    shell: bash

jobs:
  static-analysis:
    uses: armckinney/cicd/.github/workflows/rwf-terraform-static-analysis.yaml@main
    with:
      container_image: ${{ inputs.container_image }}
      configuration: ${{ inputs.configuration }}
      environment: ${{ inputs.environment }}

  terraform-plan:
    needs: static-analysis
    uses: armckinney/cicd/.github/workflows/rwf-terraform-plan.yaml@main
    with:
      container_image: ${{ inputs.container_image }}
      configuration: ${{ inputs.configuration }}
      environment: ${{ inputs.environment }}
      arm_use_oidc: ${{ inputs.arm_use_oidc }}
    secrets:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}

  terraform-apply:
    needs: terraform-plan
    uses: armckinney/cicd/.github/workflows/rwf-terraform-apply.yaml@main
    with:
      container_image: ${{ inputs.container_image }}
      configuration: ${{ inputs.configuration }}
      environment: ${{ inputs.environment }}
      arm_use_oidc: ${{ inputs.arm_use_oidc }}
    secrets:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
