name: terraform-destroy

on:
  workflow_call:
    inputs:
      review_environment:
        description: 'Name of the Github environment for review approvals'
        type: string
        required: true
      container_image:
        description: 'Container image name'
        type: string
        required: true
      tf_configuration_path:
        description: 'Filepath Terraform configuration to analyze'
        type: string
        required: true
      tf_varfile:
        description: 'Terraform environment varfile to analyze'
        type: string
        required: true
      tf_backend_config:
        description: "Terraform environment backend config"
        type: string
        required: true

defaults:
  run:
    shell: bash

jobs:
  terraform-destroy:
    runs-on: ubuntu-24.04
    environment: ${{ inputs.review_environment }}
    container:
      image: ${{ inputs.container_image }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Terraform init
      run: |
        terraform -chdir=${{ inputs.tf_configuration_path}} init -backend-config=${{ inputs.tf_backend_config }} -reconfigure

    - name: Terraform destroy
      run: |
        terraform -chdir=${{ inputs.tf_configuration_path }} destroy -auto-approve -var-file=${{ inputs.tf_varfile}}
