name: terraform-static-analysis

on:
  workflow_call:
    inputs:
      container_image:
        description: 'Container image name'
        type: string
        required: true
      tf_configuration_path:
        description: 'Filepath Terraform configuration to analyze'
        type: string
        required: true
      tf_varfile:
        description: 'Terraform environment varfile to analyze'
        type: string
        required: true

defaults:
  run:
    shell: bash

jobs:
  terraform-format:
    runs-on: ubuntu-24.04
    container:
      image: ${{ inputs.container_image }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Terraform format
      run: |
        terraform -chdir=${{ inputs.tf_configuration_path }} fmt -check

  terraform-validate:
    runs-on: ubuntu-24.04
    container:
      image: ${{ inputs.container_image }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Terraform validate
      run: |
        terraform -chdir=${{ inputs.tf_configuration_path }} init -backend=false
        terraform -chdir=${{ inputs.tf_configuration_path }} validate

  terraform-docs:
    runs-on: ubuntu-24.04
    container:
      image: ${{ inputs.container_image }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Terraform docs
      run: |
        terraform-docs --output-file TERRAFORM_DOCS.md terraform/configurations/
        cmp ${{ inputs.tf_configuration_path }}/TERRAFORM_DOCS.md ${{ inputs.tf_configuration_path }}/README.md

  terraform-security:
    runs-on: ubuntu-24.04
    container:
      image: ${{ inputs.container_image }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Terraform security
      run: |
        trivy config --tf-exclude-downloaded-modules --severity HIGH,CRITICAL --exit-code 1 ${{ inputs.tf_configuration_path}}

  terraform-lint:
    runs-on: ubuntu-24.04
    container:
      image: ${{ inputs.container_image }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Terraform lint
      run: |
        tflint --chdir=${{ inputs.tf_configuration_path }} --minimum-failure-severity=error --var-file=${{ inputs.tf_varfile }}
