name: terraform-static-analysis

on:
  workflow_call:
    inputs:
      container_image:
        description: 'Container image name'
        type: string
        required: true
      configuration:
        description: 'Name of the configuration'
        type: string
        required: true
      environment:
        description: 'Configuration Environment, should be the same for both the backend and GitHub environment'
        type: string
        required: true

defaults:
  run:
    shell: bash

jobs:
  terraform-format:
    runs-on: ubuntu-24.04
    container:
      image: ${{ inputs.container_image }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Terraform format
      uses: ./.github/actions/terraform/fmt
      with:
        configuration: ${{ inputs.configuration }}

  terraform-validate:
    runs-on: ubuntu-24.04
    container:
      image: ${{ inputs.container_image }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Terraform validate
      uses: ./.github/actions/terraform/validate
      with:
        configuration: ${{ inputs.configuration }}

  terraform-docs:
    runs-on: ubuntu-24.04
    container:
      image: ${{ inputs.container_image }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Terraform docs
      uses: ./.github/actions/terraform/docs
      with:
        configuration: ${{ inputs.configuration }}

  terraform-security:
    runs-on: ubuntu-24.04
    container:
      image: ${{ inputs.container_image }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Terraform security
      uses: ./.github/actions/terraform/security
      with:
        configuration: ${{ inputs.configuration }}

  terraform-lint:
    runs-on: ubuntu-24.04
    container:
      image: ${{ inputs.container_image }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Terraform lint
      uses: ./.github/actions/terraform/lint
      with:
        configuration: ${{ inputs.configuration }}
        environment: ${{ inputs.environment }}
