name: python-build-and-publish

on:
  workflow_call:
    inputs:
      container_image:
        description: 'Container image name'
        type: string
        required: true
      working_directory:
        description: 'Directory to build and publish from'
        type: string
        required: false
        default: '.'
      skip_publish:
        description: 'Skip the publish step (build only)'
        type: boolean
        required: false
        default: false

defaults:
  run:
    shell: bash

jobs:
  build-and-publish:
    runs-on: ubuntu-24.04
    container:
      image: ${{ inputs.container_image }}
    permissions:
      packages: write
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build Python package
      working-directory: ${{ inputs.working_directory }}
      run: |
        uv build

    - name: Publish Python package
      if: ${{ !inputs.skip_publish }}
      working-directory: ${{ inputs.working_directory }}
      run: |
        uv publish \
          --publish-url https://pypi.pkg.github.com/${{ github.repository_owner }}/ \
          --token ${{ github.token }}
