name: terraform-destroy

on:
  workflow_call:
    inputs:
      container_image:
        description: 'Container image name'
        type: string
        required: true
      configuration:
        description: 'Name of the configuration'
        type: string
        required: true
      environment:
        description: 'Configuration Environment, should be the same for both the backend and GitHub environment'
        type: string
        required: true
    secrets:
      ARM_CLIENT_ID:
        description: 'Azure Service Principal Client ID'
        required: false
      ARM_SUBSCRIPTION_ID:
        description: 'Azure Subscription ID'
        required: false
      ARM_TENANT_ID:
        description: 'Azure Tenant ID'
        required: false
      ARM_CLIENT_SECRET:
        description: 'Azure Service Principal Client Secret'
        required: false

defaults:
  run:
    shell: bash

jobs:
  terraform-destroy:
    runs-on: ubuntu-24.04
    environment: ${{ inputs.environment }}
    container:
      image: ${{ inputs.container_image }}

    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Terraform init
        run: |
          terraform -chdir=terraform/configurations/${{ inputs.configuration }} init -backend-config=env/${{ inputs.environment }}.tfbackend -reconfigure

      - name: Terraform destroy
        run: |
          terraform -chdir=terraform/configurations/${{ inputs.configuration }} destroy -auto-approve -var-file=env/${{ inputs.environment }}.tfvars
