name: TerraformCI

env:
  DOCKERHUB_ID: 'armck'
  TF_CONFIGURATION_PATH: 'terraform/configurations/example'
  TF_VARFILE: 'env/dev.tfvars'
  TF_BACKEND_CONFIG: 'env/dev.tfbackend'

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

defaults:
  run:
    shell: bash

jobs:
  setup-env:
    runs-on: ubuntu-24.04
    outputs:
        dockerhub_id: ${{ steps.env.outputs.dockerhub_id }}
        tf_configuration_path: ${{ steps.env.outputs.tf_configuration_path }}
        tf_varfile: ${{ steps.env.outputs.tf_varfile }}
        tf_backend_config: ${{ steps.env.outputs.tf_backend_config }}
    steps:
      - name: Setup environment variables
        id: env
        run: |
          echo "dockerhub_id=$DOCKERHUB_ID" >> "$GITHUB_OUTPUT"
          echo "tf_configuration_path=$TF_CONFIGURATION_PATH" >> "$GITHUB_OUTPUT"
          echo "tf_varfile=$TF_VARFILE" >> "$GITHUB_OUTPUT"
          echo "tf_backend_config=$TF_BACKEND_CONFIG" >> "$GITHUB_OUTPUT"

  container-build-and-push:
    uses: armckinney/cicd/.github/workflows/container-build-and-push.yaml@1-scaffold-project
    needs: setup-env
    with:
      dockerhub_id: ${{ needs.setup-env.outputs.dockerhub_id }}
    secrets:
      DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

  static-analysis:
    needs: [container-build-and-push, setup-env]
    uses: armckinney/cicd/.github/workflows/terraform-static-analysis.yaml@1-scaffold-project
    with:
      container_image: ${{ needs.container-build-and-push.outputs.container_image }}
      tf_configuration_path: ${{ needs.setup-env.outputs.tf_configuration_path }}
      tf_varfile: ${{ needs.setup-env.outputs.tf_varfile }}

  terraform-plan:
    needs: [container-build-and-push, setup-env]
    runs-on: ubuntu-24.04
    container:
      image: ${{ needs.container-build-and-push.outputs.container_image }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Terraform lint
      uses: ./platforms/github/composite-actions/terraform-plan
      with:
        tf_configuration_path: ${{ needs.setup-env.outputs.tf_configuration_path }}
        tf_varfile: ${{ needs.setup-env.outputs.tf_varfile }}

  # terreaform-commands: todo
    # needs an environment for review
  #   uses: armckinney/cicd/.github/workflows/terraform-commands.yaml@1-scaffold-project
  #   with:
  #     configuration: "todo"
  #     environment: "todo"
