name: TerraformCI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  container-build-and-push:
    uses: armckinney/cicd/.github/workflows/container-build-and-push.yaml@1-scaffold-project
    secrets:
      DOCKER_HUB_ID: ${{ secrets.DOCKER_HUB_ID }}
      DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

  static-analysis:
    needs: container-build-and-push
    uses: armckinney/cicd/.github/workflows/terraform-static-analysis.yaml@1-scaffold-project
    with:
      configuration: example
      environment: dev
      container_image: ${{ needs.container-build-and-push.outputs.container_image }}

  # terraform-plan:
    # implement as CA

  # terreaform-commands:
    # needs an environment for review
  #   uses: armckinney/cicd/.github/workflows/terraform-commands.yaml@1-scaffold-project
  #   with:
  #     configuration: "todo"
  #     environment: "todo"
