name: wf-container-build-and-push

on: 
  workflow_dispatch:
    inputs:
      dockerfile:
        description: "Filepath of dockerfile to build and push"
        type: string
        required: false
        default: "./.devcontainer/Dockerfile"
      image_name: 
        description: "Name of the Docker image to build and push"
        type: string
        required: false
        default: cicd
      image_tag:
        description: "Tag to use for the Docker image"
        type: string
        required: false
        default: wf-container-build-and-push

defaults:
  run:
    shell: bash

jobs:
  container-build-and-push:
    uses: ./.github/workflows/rwf-container-build-and-push.yaml
    with:
      dockerfile: ${{ inputs.dockerfile }}
      image_name: ${{ inputs.image_name }}
      image_tag: ${{ inputs.image_tag }}
