name: wf-terraform-apply

on:
  workflow_dispatch:
    inputs:
      configuration:
        description: 'Name of the configuration'
        required: true
        type: choice
        options:
        - example
      environment:
        description: 'Configuration Environment, should be the same for both the backend and GitHub environment'
        required: true
        type: choice
        options:
        - dev
        - test
        - prod

defaults:
  run:
    shell: bash

jobs:
  container-build-and-push:
    uses: ./.github/workflows/rwf-container-build-and-push.yaml

  static-analysis:
    needs: [container-build-and-push]
    uses: ./.github/workflows/rwf-terraform-static-analysis.yaml
    with:
      container_image: ${{ needs.container-build-and-push.outputs.container_image }}
      configuration: ${{ inputs.configuration }}
      environment: ${{ inputs.environment }}

  terraform-plan:
    needs: [container-build-and-push, static-analysis]
    uses: ./.github/workflows/rwf-terraform-plan.yaml
    with:
      container_image: ${{ needs.container-build-and-push.outputs.container_image }}
      configuration: ${{ inputs.configuration }}
      environment: ${{ inputs.environment }}

  terraform-apply:
    needs: [container-build-and-push, terraform-plan]
    uses: ./.github/workflows/rwf-terraform-apply.yaml
    with:
      container_image: ${{ needs.container-build-and-push.outputs.container_image }}
      configuration: ${{ inputs.configuration }}
      environment: ${{ inputs.environment }}
