name: tag-semver

on:
  push:
    branches: ["**"]
    tags-ignore: ["**"]

jobs:
  tag-semver:
    uses: ./.github/workflows/rwf-tag-semver.yaml
    secrets: inherit
    with:
      prerelease_label: ${{ github.ref_name != github.event.repository.default_branch && '-dev' || '' }}
