name: wf-terraform-ci-azurerg-dev

env:
  DOCKERHUB_ID: 'armck'
  CONFIGURATION: 'azurerg'
  ENVIRONMENT: 'dev'

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  setup-env:
    runs-on: ubuntu-24.04
    outputs:
        dockerhub_id: ${{ steps.env.outputs.dockerhub_id }}
        configuration: ${{ steps.env.outputs.configuration }}
        environment: ${{ steps.env.outputs.environment }}
    steps:
      - name: Setup environment variables
        id: env
        run: |
          echo "dockerhub_id=$DOCKERHUB_ID" >> "$GITHUB_OUTPUT"
          echo "configuration=$CONFIGURATION" >> "$GITHUB_OUTPUT"
          echo "environment=$ENVIRONMENT" >> "$GITHUB_OUTPUT"

  container-build-and-push:
    needs: setup-env
    uses: armckinney/cicd/.github/workflows/rwf-container-build-and-push.yaml@main
    with:
      dockerhub_id: ${{ needs.setup-env.outputs.dockerhub_id }}
    secrets:
      DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

  terraform-deployment-ci:
    needs: [setup-env, container-build-and-push]
    uses: armckinney/cicd/.github/workflows/rwf-terraform-deployment-ci.yaml@main
    with:
      container_image: ${{ needs.container-build-and-push.outputs.container_image }}
      configuration: ${{ needs.setup-env.outputs.configuration }}
      environment: ${{ needs.setup-env.outputs.environment }}
    secrets:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}

  # note: this is just for testing purposes, it will destroy the resources created by the terraform-deployment-ci job
  terraform-destroy:
    needs: [setup-env, container-build-and-push, terraform-deployment-ci]
    uses: armckinney/cicd/.github/workflows/rwf-terraform-destroy.yaml@main
    with:
      container_image: ${{ needs.container-build-and-push.outputs.container_image }}
      configuration: ${{ needs.setup-env.outputs.configuration }}
      environment: ${{ needs.setup-env.outputs.environment }}
    secrets:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
