name: wf-tag-semver

on:
  push:
    branches: ["**"]
    tags-ignore: ["**"]

jobs:
  tag-semver:
    uses: ./.github/workflows/rwf-verge-tag.yaml
    secrets: inherit
    with:
      prune_dev_tags: ${{ github.ref_name == github.event.repository.default_branch }}

